-- ERA Custom: weaponskill skill requirements from era.
-- 358 can't be reached at level 75, which keeps post-era weaponskills (Relic, Empyrean, Abyssea) unusable.

UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 10; -- final_heaven
UPDATE `weapon_skills` SET `skilllevel` = 250 WHERE `weaponskillid` = 11; -- ascetics_fury
UPDATE `weapon_skills` SET `skilllevel` = 250 WHERE `weaponskillid` = 12; -- stringing_pummel
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 13; -- tornado_kick
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 14; -- victory_smite
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 15; -- shijin_spiral
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 26; -- mercy_stroke
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 27; -- mandalic_stab
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 28; -- mordant_rime
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 29; -- pyrrhic_kleos
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 30; -- aeolian_edge
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 31; -- rudras_storm
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 43; -- knights_of_round
UPDATE `weapon_skills` SET `skilllevel` = 240 WHERE `weaponskillid` = 44; -- death_blossom
UPDATE `weapon_skills` SET `skilllevel` = 240 WHERE `weaponskillid` = 45; -- atonement
UPDATE `weapon_skills` SET `skilllevel` = 240 WHERE `weaponskillid` = 46; -- expiacion
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 47; -- sanguine_blade
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 57; -- scourge
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 58; -- herculean_slash
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 59; -- torcleaver
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 60; -- resolution
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 73; -- onslaught
UPDATE `weapon_skills` SET `skilllevel` = 240 WHERE `weaponskillid` = 74; -- primal_rend
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 75; -- bora_axe
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 76; -- cloudsplitter
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 77; -- ruinator
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 89; -- metatron_torment
UPDATE `weapon_skills` SET `skilllevel` = 240 WHERE `weaponskillid` = 90; -- kings_justice
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 91; -- fell_cleave
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 92; -- ukkos_fury
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 93; -- upheaval
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 105; -- catastrophe
UPDATE `weapon_skills` SET `skilllevel` = 240 WHERE `weaponskillid` = 106; -- insurgency
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 107; -- infernal_scythe
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 108; -- quietus
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 109; -- entropy
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 121; -- geirskogul
UPDATE `weapon_skills` SET `skilllevel` = 240 WHERE `weaponskillid` = 122; -- drakesbane
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 123; -- sonic_thrust
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 124; -- camlanns_torment
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 125; -- stardiver
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 137; -- blade_metsu
UPDATE `weapon_skills` SET `skilllevel` = 250 WHERE `weaponskillid` = 138; -- blade_kamu
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 139; -- blade_yu
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 140; -- blade_hi
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 141; -- blade_shun
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 153; -- tachi_kaiten
UPDATE `weapon_skills` SET `skilllevel` = 250 WHERE `weaponskillid` = 154; -- tachi_rana
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 155; -- tachi_ageha
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 156; -- tachi_fudo
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 157; -- tachi_shoha
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 170; -- randgrith
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 171; -- mystic_boon
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 172; -- flash_nova
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 173; -- dagan
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 174; -- realmrazer
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 185; -- gate_of_tartarus
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 186; -- vidohunir
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 187; -- garland_of_bliss
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 188; -- omniscience
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 189; -- cataclysm
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 190; -- myrkr
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 191; -- shattersoul
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 200; -- namas_arrow
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 201; -- refulgent_arrow
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 202; -- jishnus_radiance
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 203; -- apex_arrow
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 216; -- coronach
UPDATE `weapon_skills` SET `skilllevel` = 250 WHERE `weaponskillid` = 217; -- trueflight
UPDATE `weapon_skills` SET `skilllevel` = 250 WHERE `weaponskillid` = 218; -- leaden_salute
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 219; -- numbing_shot
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 220; -- wildfire
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 221; -- last_stand
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 224; -- exenterator
UPDATE `weapon_skills` SET `skilllevel` = 358 WHERE `weaponskillid` = 225; -- chant_du_cygne
UPDATE `weapon_skills` SET `skilllevel` = 230 WHERE `weaponskillid` = 226; -- requiescat
UPDATE `weapon_skills` SET `skilllevel` = 240 WHERE `weaponskillid` = 238; -- uriel_blade
UPDATE `weapon_skills` SET `skilllevel` = 240 WHERE `weaponskillid` = 239; -- glory_slash
UPDATE `weapon_skills` SET `skilllevel` = 240 WHERE `weaponskillid` = 240; -- tartarus_torpor
